plugins {
    id 'java'
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0" apply false
}

if (gradle.startParameter.taskNames.any { it.toLowerCase().contains("curseforge") }) {
    apply plugin: "com.matthewprenger.cursegradle"
}
base {
    archivesName = project.archives_base_name
}
java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}


def getDependencies(project, List<String> depNames, configuration) {
    return depNames.iterator().collect {
        project.dependencies.project(path: ":$it")
    }
}

apply from: "functions.gradle"
apply from: "common.gradle"
apply from: "helper.gradle"
