plugins {
    id 'java'
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}
base {
    archivesName = project.archives_base_name
}
java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}


def getDependencies(project, List<String> depNames, configuration) {
    return depNames.iterator().collect {
        project.dependencies.project(path: ":WorldWeaver:$it")
    }
}

apply from: "functions.gradle"
apply from: "common.gradle"
